@startuml
participant FrontEnd
participant API
database DB

FrontEnd -> API: Submit new store data
alt Successful case

ref over API, DB : validate_user_has_store


API -> API: Create new store
API -> API: Create default store settings
API -> DB: Save store & settings

alt Successful case
DB -> API: ok
else Error
DB --> API: Error
end
API -> FrontEnd: Store created
FrontEnd -> FrontEnd: Show store settings

else Failure
API --> FrontEnd: Store name already in use
else Error
API --> FrontEnd: Error
end


@enduml